// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VzkxqulCpJt21zg90cHxLgPuazcxiPE',
    appId: '1:1077109706182:web:d020e74497129faf8c36c7',
    messagingSenderId: '1077109706182',
    projectId: 'mcproject-680fd',
    authDomain: 'mcproject-680fd.firebaseapp.com',
    storageBucket: 'mcproject-680fd.appspot.com',
    measurementId: 'G-5ZLX2DH2K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAZ2yGbKeLEHV52JO3_IghC-LuQoIR7k',
    appId: '1:1077109706182:android:c7bc601b52787ec58c36c7',
    messagingSenderId: '1077109706182',
    projectId: 'mcproject-680fd',
    storageBucket: 'mcproject-680fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmC5-JcAKoG-NkzO8OJvISMVA1SFHBQUE',
    appId: '1:1077109706182:ios:a11f6fe1d574ea588c36c7',
    messagingSenderId: '1077109706182',
    projectId: 'mcproject-680fd',
    storageBucket: 'mcproject-680fd.appspot.com',
    iosBundleId: 'com.example.mcproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmC5-JcAKoG-NkzO8OJvISMVA1SFHBQUE',
    appId: '1:1077109706182:ios:a11f6fe1d574ea588c36c7',
    messagingSenderId: '1077109706182',
    projectId: 'mcproject-680fd',
    storageBucket: 'mcproject-680fd.appspot.com',
    iosBundleId: 'com.example.mcproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3VzkxqulCpJt21zg90cHxLgPuazcxiPE',
    appId: '1:1077109706182:web:c7b12b4c48ab0fbf8c36c7',
    messagingSenderId: '1077109706182',
    projectId: 'mcproject-680fd',
    authDomain: 'mcproject-680fd.firebaseapp.com',
    storageBucket: 'mcproject-680fd.appspot.com',
    measurementId: 'G-QF6C1VRRXC',
  );
}
